### ISSUE TITLE
9주차-1 (월)

### ISSUE THREAD

**Issue by hanjo8813** [study-for-interview/algorithm-study#1]
### 추천문제

|카테고리|난이도|문제명|링크|
|---|---|---|---|
|그래프탐색|level 3|여행경로|https://programmers.co.kr/learn/courses/30/lessons/43164|
|그래프탐색|Gold 4|숨바꼭질4|https://www.acmicpc.net/problem/13913|
|최단경로|Gold 4|운동|https://www.acmicpc.net/problem/1956|
|최단경로|Gold 3|파티|https://www.acmicpc.net/problem/1238|

**Comment by jcu011** [comment]
| 난이도 | 문제 번호 | 문제 이름 |
|:------:|:----:|:---------:|
| `Level 2` | [2018 KAKAO BLIND RECRUITMENT](https://programmers.co.kr/learn/challenges) | [[1차] 캐시](https://programmers.co.kr/learn/courses/30/lessons/17680) |

**Comment by jerry0339** [comment]
https://programmers.co.kr/learn/courses/30/lessons/17676

**Comment by choiyoungkwon12** [comment]
https://www.acmicpc.net/problem/16234
