### ISSUE TITLE
10주차-1 (월)

### ISSUE THREAD

**Issue by jerry0339** [study-for-interview/algorithm-study#11]
### 추천 문제 List

| 난이도 | 문제 번호 | 문제 이름 |
|:------:|:----:|:---------:|
| <img height="25px" width="25px" src="https://static.solved.ac/tier_small/12.svg"/> | [13913](https://www.acmicpc.net/problem/13913) | [숨바꼭질 4](https://www.acmicpc.net/problem/13913) |
| <img height="25px" width="25px" src="https://static.solved.ac/tier_small/12.svg"/> | [1956](https://www.acmicpc.net/problem/1956) | [운동](https://www.acmicpc.net/problem/1956) |
| `Level 3` | [프로그래머스 코테 연습](https://programmers.co.kr/learn/courses/30/lessons/43164) | [여행경로](https://programmers.co.kr/learn/courses/30/lessons/43164) |
| `Level 3` | [2017 카카오 코드 페스티벌](https://programmers.co.kr/learn/courses/30/lessons/1830) | [브라이언의 고민](https://programmers.co.kr/learn/courses/30/lessons/1830) |

**Comment by jerry0339** [comment]
https://www.acmicpc.net/problem/5588

**Comment by sunH0** [comment]
https://www.acmicpc.net/problem/2096
