### ISSUE TITLE
9주차-2 (목)

### ISSUE THREAD

**Issue by jerry0339** [study-for-interview/algorithm-study#7]

**Comment by jerry0339** [comment]
https://www.acmicpc.net/problem/4485

**Comment by sunH0** [comment]
https://www.acmicpc.net/problem/1670
조합

**Comment by hanjo8813** [comment]
카카오 레벨 2 주차요금계산
https://programmers.co.kr/learn/courses/30/lessons/92341

**Comment by GetMapping** [comment]
카카오 레벨 2 브라이언의 고민
https://programmers.co.kr/learn/courses/30/lessons/1830
